# Generated by Django 3.1.7 on 2021-05-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('specialist_in', models.CharField(max_length=120)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
